### ISSUE TITLE
dynamic configuration for PHPUnit

### ISSUE THREAD

**Issue by DanielRuf** [Maikuolan/phpMussel-extras#4]
I will try these solutions for changing the configuration dynamically for specific unit tests.

https://github.com/pear/Config_Lite
https://github.com/pear/Config
http://stackoverflow.com/questions/5695145/how-to-read-and-write-to-an-ini-file-with-php

`preg_replace()` and more

**Comment by DanielRuf** [comment]
Config_Lite and Config worked without any issues.

Keep in mind to properly typecast values from ini files to the right data type (string, int, boolean, ...).

https://github.com/Maikuolan/phpMussel-extras/pull/5

This can be also used for a possible future installer (write config file and keep comments, use Config instead of Config_Lite, Config_Lite can be used for PHPUnit tests).

Do we really need 0 and 1 in the config file instead of true and false? Was just curious why this is so. But it would be safe to keep the current values like they are and typecast them in phpMussel.

**Comment by Maikuolan** [comment]
Functionally, there shouldn't be any difference between 0/false or 1/true (assuming there isn't any `===` type matching, but only `==` value matching), but, if we could typecast directives properly, that would be preferable to what we've currently got, as so that phpMussel could be more semantically accurate in the way it handles/reads/writes variables.

The reason for it being the way it is, mostly is simply that in the earliest days of phpMussel development, when new directives were being created on an almost daily basis, it was just slightly easier, quicker and lazier to write `="1"` or `="0"` instead of `=true` or `=false`, and since those days, changing it just isn't something I'd really thought much about (if it worked correctly, and other things didn't work, or other functions/capabilities weren't yet completed/implemented, the things that didn't work or that weren't yet completed/implemented were always going to be more at the front of my thoughts than those things that worked correctly).

Although I hadn't thought about it, now that you've mentioned it, I do think directives should be correctly typecasted; Probably both by the INI defaults as well as by the core script, because it's possible that users might potentially change something to an incorrect/invalid value, which could potentially throw out typecasting, too.

**Comment by Maikuolan** [comment]
(( The one important caveat to the aforementioned explanation to remember, though, is for some particular directives that can have more than two possible values, such as the `vt_suspicion_level` directive, for example. Directives that are strictly 1/0 YES/NO directives, though, could be changed to TRUE/FALSE to reflect correct typecasting. ))

**Comment by DanielRuf** [comment]
Right, `(int)`, `(boolean)` and other typecasts can be used in the future but this also comes with changes in many scripts.

Just something I noticed while testing Config and Config_Lite but nothing critical. As long as people read the comments and use the right values (which are also mentioned in the documentation) it should be no problem (then at least internal typecasting in the core script would make sense if someone inputs wrong values).

For now I would let it how it is.

But the examples with Config and Config_Lite can help us to run PHPUnit tests with different configuration values and eases the implementation for CMS as they can easily make changes to the configuration without reinventing the wheel and writing own and possibly buggy solutions to change the configuration file.

When I find the time I will create some simple basic installer for testing purposes and and to see if we can streamline the implementation into CMS by providing solutions like a configuration script like these examples with Config and Config_Lite.

**Comment by Maikuolan** [comment]
Cool, sounds good. :-)

**Comment by Maikuolan** [comment]
Closing because stale.
